version: 2.1

# commands:
#   sayhello:
#     description: "description of 'sayhello command'"
#     parameters:
#       to:
#         type: string
#         default: "SAY HELLO for deloyment process"
#     steps:
#       - run: echo <<parameters.to>>

executors:
  my-executor:
    docker:
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run

jobs:
  building:
    executor: my-executor
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
        keys:
          - v1-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
        key: v1-deps-{{ checksum "package-lock.json" }}
        paths:
          - node_modules

workflows:
  version: 2
  building_and_deployment: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - building:
